### ISSUE TITLE
[FE] api 로직 제네릭으로 변경

### ISSUE THREAD

**Issue by chlwlstlf** [woowacourse-teams/2024-corea#296]
## ✨ 세부 내용

- 요청 타입과 반환 타입을 정확히 몰라서 api 로직을 파악하는 데 시간이 걸렸습니다.
- 이를 해결하고자 제네릭 타입을 도입하고 api 로직을 변경할 예정입니다.

## ⏰ 예상 소요 시간

2시간

**Comment by 00kang** [comment]
시간 관계상 close,,
