### ISSUE TITLE
[BE] 코드 자동 정렬

### ISSUE THREAD

**Issue by jcoding-play** [woowacourse-teams/2024-corea#328]
## ✨ 세부 내용

단축키를 이용하여 코드 자동 정렬 기능을 수행합니다.
이전 pr에 같이 푸시하려고 했는데, file changes가 많이 나와서 코드 리뷰가 어려우실 것 같아 이슈 분리했습니다! 😭

## ⏰ 예상 소요 시간

1분

**Comment by ashsty** [comment]
배려굿이여
