### ISSUE TITLE
[FE] 랭킹 페이지 수정

### ISSUE THREAD

**Issue by chlwlstlf** [woowacourse-teams/2024-corea#360]
## ✨ 세부 내용

- 프로필 누르면 깃허브로 넘어가게 하기
- 랭킹 페이지 아이콘 추가

## ⏰ 예상 소요 시간

30분

**Comment by 00kang** [comment]
현재 목표하고 있는 프리코스 때 랭킹 서비스를 제공하지 않을 계획, 그래서 close,,
