### ISSUE TITLE
[BE] 내부 로직 - 방 참여

### ISSUE THREAD

**Issue by ashsty** [woowacourse-teams/2024-corea#37]
## ✨ 세부 내용
리뷰를 원하는 사람들이 원하는 방에 참여하는 기능을 구현합니다.

## ⏰ 예상 소요 시간
1시간 이내

**Comment by youngsu5582** [comment]
#32 [BE] 메인 페이지 - 방 신청 버튼 API 내용과 뭐가 다른거야??

**Comment by ashsty** [comment]
> #32 [BE] 메인 페이지 - 방 신청 버튼 API 내용과 뭐가 다른거야??

생각해보니까 다른 게 없는듯 합니다?

해커톤 구현 시 해당 버튼이 없어서 내부 로직만 있고 외부 노출 API가 없었는데
해커톤 기능 명세 옮겨오다가 실수가 있었던 모양입니다용.
  
그냥 close할게용 ㅎㅎ
